# Generated by Django 5.1.2 on 2024-11-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eezy', '0002_alter_eezy_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eezy',
            name='user',
        ),
    ]
