# Generated by Django 4.2.14 on 2024-11-13 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eezy", "0004_eezy_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eezy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 11, 13, 8, 31, 2, 256049, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
