# Generated by Django 5.1.2 on 2024-11-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eezy_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='squeezy_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
