# Generated by Django 5.1.2 on 2024-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='squeezy_count',
            new_name='squeeze_count',
        ),
    ]
