# Generated by Django 4.2.14 on 2024-11-13 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squeeze", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="squeeze",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 11, 13, 8, 31, 5, 947044, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
