# Generated by Django 5.1.2 on 2024-11-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squeeze', '0001_initial'),
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squeeze',
            name='tabs',
            field=models.ManyToManyField(to='tabs.tab'),
        ),
    ]
