# Generated by Django 5.1.2 on 2024-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squeeze', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squeeze',
            name='image',
        ),
        migrations.AddField(
            model_name='squeeze',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
